### ISSUE TITLE
Error in switching games

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/pgn-viewer#563]
### Discussed in https://github.com/mliebelt/pgn-viewer/discussions/562

<div type='discussions-op-text'>

<sup>Originally posted by **Huub62** August 19, 2024</sup>
I am new to using this script so please forgive me if i ask something thats obvious for many of you.

I made a custom layout for a pgn viewer and all worked really well. But i ran into a problem when i tried to upload a pgn file with multiple games in it.

First i checked the example on: https://mliebelt.github.io/pgn-viewer/examples/1101.html

Then worked on some code to upload the pgn file and process it correctly. But when i tested it, the dropdownlist was indeed filled and the first game could be played, but as soon as i choose another from the dropdownlist this error showed up: 

```
dist.js:1 Uncaught TypeError: Cannot read properties of null (reading 'parentNode')
    at i (dist.js:1:951316)
    at HTMLSelectElement.<anonymous> (dist.js:1:950460)
```
   
Of course i checked the pgn file but it pasted the test in the Lichess editor and i also tried some very simple pgn files, but the error remained. When i looked back at the website: https://mliebelt.github.io/pgn-viewer/examples/1101.html and opened the console i noticed it showed the same error. Can someone please help me solve this issue. What i hope to accomplish is to have a uploadfile button on my page that gets the dropdownlist filled with the games and that they can be played back. As it is now i not only get the error but also the board doesnt update to the new game choosen from the dropdownlist. So, right now it is useless. My current code is:

 

    
```
            document.getElementById('pgnFile').addEventListener('change', function(event) {
            const file = event.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    const pgnText = e.target.result;    
                    loadPgn(pgnText);
                };
                reader.readAsText(file);
            }
        });
    
        function loadPgn(pgnText) {
            pgnv = PGNV.pgnView("board", {
                pgn: pgnText,
                manyGames: true,
                showCoords: true, 
                orientation: 'white', 
                theme: 'brown', 
                pieceStyle: 'merida',
                figurine: 'merida', 
                locale: 'nl', 
                width: '770px', 
                boardsize: '400px', 
                layout: 'right', 
                timerTime: 0, 
                coordsInner: true, 
                coordsFactor: 1.0,
                coordsFontSize: 14, 
                notation: 'short', 
                notationLayout: 'list', 
                hideMovesBefore: false, 
                showFen: false, 
                colorMarker: 'cm-big'
            });
        }
    
        window.onload = function() {
            loadPgn('');
        };

```
Thank you all in advance for any help and wishing you all a wonderful day!</div>

**Comment by mliebelt** [comment]
Created a new release 1.6.9, pushed it to npmjs, and deployed it to Github pages as well. The example https://mliebelt.github.io/pgn-viewer/examples.html#1101 should now work as expected, without an error. Hopefully that fixes the error of @Huub62 as well.
