### ISSUE TITLE
PgnViewer fails on moves input with D for diagrams

### ISSUE THREAD

**Issue by Bebul** [mliebelt/pgn-viewer#580]
Before it was possible to have the letter `D` at the end of move to make the PgnView render the diagram as shown at the following screenshot (I have checkouted version +/- March 2021 to see how it was at that time.)

![image](https://github.com/user-attachments/assets/d905308a-9836-4bff-ab0a-873b863b2ccc)

Where the move list in PGN contains letter D at the end of the move:
```
1. d4 e6 2. Nc3 d5 3. Bf4D?!
```

But now, the PgnViewer in Configuration builder fails with
```
index.umd.js:11137 Uncaught Error: No legal move: d4
    at index.umd.js:11137:19
    at Array.forEach (<anonymous>)
    at g (index.umd.js:11101:32)
    at c.eachMove (index.umd.js:11171:18)
    at c.readMoves (index.umd.js:10837:35)
    at c.loadOne (index.umd.js:10772:31)
    at c.loadPgn (index.umd.js:10735:24)
    at new c (index.umd.js:10697:10)
    at FA (dist.js:1:1009624)
    at dist.js:1:1018201
```

**Comment by mliebelt** [comment]
Thank you for bringing that up, should be a regression in one of the latest versions. I will check some time later if it is easy to bring back then.

**Comment by mliebelt** [comment]
Had lately a fix for the similar case, where $220 or $221 (white or black view of the current board) stopped the reader to print the moves. I had added the annotation "D" before I was aware of $220 and $221 (which is more exact, because it gives you as well the orientation of the board). I have to check that again, perhaps replacing the old annotation or interpreting it as $220 or $221 depending on which move that comes.

**Comment by mliebelt** [comment]
Working again, added an example how it works. Will be included in the next version is a few days.
